#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

#This is specific to you module, so you need to change it accordingly.
#agent.dump_env()
TZ = data.get("TZ", "${TZ}") 
SKIP_UNBOUND_HEALTHCHECK = data.get("SKIP_UNBOUND_HEALTHCHECK", "${SKIP_UNBOUND_HEALTHCHECK:-n}") 
 
unbound-mailcow = { 
 "TZ" : TZ ,
 "SKIP_UNBOUND_HEALTHCHECK" : SKIP_UNBOUND_HEALTHCHECK ,
} 
agent.write_envfile("unbound-mailcow.env", unbound-mailcow) 
TZ = data.get("TZ", "${TZ}") 
SKIP_CLAMD = data.get("SKIP_CLAMD", "${SKIP_CLAMD:-n}") 
 
clamd-mailcow = { 
 "TZ" : TZ ,
 "SKIP_CLAMD" : SKIP_CLAMD ,
} 
agent.write_envfile("clamd-mailcow.env", clamd-mailcow) 
DBNAME = data.get("DBNAME", "${DBNAME}") 
TZ = data.get("TZ", "${TZ}") 
LOG_LINES = data.get("LOG_LINES", "${LOG_LINES:-9999}") 
MAILCOW_PASS_SCHEME = data.get("MAILCOW_PASS_SCHEME", "${MAILCOW_PASS_SCHEME:-BLF-CRYPT}") 
MASTER = data.get("MASTER", "${MASTER:-y}") 
DBPASS = data.get("DBPASS", "${DBPASS}") 
MAILCOW_HOSTNAME = data.get("MAILCOW_HOSTNAME", "${MAILCOW_HOSTNAME}") 
SOGO_URL_ENCRYPTION_KEY = data.get("SOGO_URL_ENCRYPTION_KEY", "${SOGO_URL_ENCRYPTION_KEY:-SOGoSuperSecret0}") 
SKIP_SOGO = data.get("SKIP_SOGO", "${SKIP_SOGO:-n}") 
REDIS_SLAVEOF_PORT = data.get("REDIS_SLAVEOF_PORT", "${REDIS_SLAVEOF_PORT:-}") 
ACL_ANYONE = data.get("ACL_ANYONE", "${ACL_ANYONE:-disallow}") 
ALLOW_ADMIN_EMAIL_LOGIN = data.get("ALLOW_ADMIN_EMAIL_LOGIN", "${ALLOW_ADMIN_EMAIL_LOGIN:-n}") 
REDISPASS = data.get("REDISPASS", "${REDISPASS}") 
DBUSER = data.get("DBUSER", "${DBUSER}") 
IPV4_NETWORK = data.get("IPV4_NETWORK", "${IPV4_NETWORK:-172.22.1}") 
SOGO_EXPIRE_SESSION = data.get("SOGO_EXPIRE_SESSION", "${SOGO_EXPIRE_SESSION:-480}") 
REDIS_SLAVEOF_IP = data.get("REDIS_SLAVEOF_IP", "${REDIS_SLAVEOF_IP:-}") 
 
sogo-mailcow = { 
 "DBNAME" : DBNAME ,
 "TZ" : TZ ,
 "LOG_LINES" : LOG_LINES ,
 "MAILCOW_PASS_SCHEME" : MAILCOW_PASS_SCHEME ,
 "MASTER" : MASTER ,
 "DBPASS" : DBPASS ,
 "MAILCOW_HOSTNAME" : MAILCOW_HOSTNAME ,
 "SOGO_URL_ENCRYPTION_KEY" : SOGO_URL_ENCRYPTION_KEY ,
 "SKIP_SOGO" : SKIP_SOGO ,
 "REDIS_SLAVEOF_PORT" : REDIS_SLAVEOF_PORT ,
 "ACL_ANYONE" : ACL_ANYONE ,
 "ALLOW_ADMIN_EMAIL_LOGIN" : ALLOW_ADMIN_EMAIL_LOGIN ,
 "REDISPASS" : REDISPASS ,
 "DBUSER" : DBUSER ,
 "IPV4_NETWORK" : IPV4_NETWORK ,
 "SOGO_EXPIRE_SESSION" : SOGO_EXPIRE_SESSION ,
 "REDIS_SLAVEOF_IP" : REDIS_SLAVEOF_IP ,
} 
agent.write_envfile("sogo-mailcow.env", sogo-mailcow) 
