#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

#This is specific to you module, so you need to change it accordingly.
#agent.dump_env()
TZ = data.get("TZ", "${TZ}") 
SKIP_UNBOUND_HEALTHCHECK = data.get("SKIP_UNBOUND_HEALTHCHECK", "${SKIP_UNBOUND_HEALTHCHECK:-n}") 
 
unbound-mailcow = { 
 "TZ" : TZ ,
 "SKIP_UNBOUND_HEALTHCHECK" : SKIP_UNBOUND_HEALTHCHECK ,
} 
agent.write_envfile("unbound-mailcow.env", unbound-mailcow) 
TZ = data.get("TZ", "${TZ}") 
SKIP_CLAMD = data.get("SKIP_CLAMD", "${SKIP_CLAMD:-n}") 
 
clamd-mailcow = { 
 "TZ" : TZ ,
 "SKIP_CLAMD" : SKIP_CLAMD ,
} 
agent.write_envfile("clamd-mailcow.env", clamd-mailcow) 
