#
# Roundcube state/backup include patterns for Restic
# Syntax reference: https://pkg.go.dev/path/filepath#Glob
# Restic --files-from: https://restic.readthedocs.io/en/stable/040_backup.html#including-files
# List here what you want to save during backup : volumes or file Path



state/unbound-mailcow.env 

volumes/hooks-unbound
volumes/conf-unbound-unboundconf
state/clamd-mailcow.env 

volumes/conf-clamav-
volumes/clamd-db-vol-1
state/sogo-mailcow.env 

volumes/hooks-sogo
volumes/conf-sogo-
volumes/web-inc-initdbincphp
volumes/conf-sogo-custom-faviconico
volumes/conf-sogo-custom-shortlogosvg
volumes/conf-sogo-custom-fulllogosvg
volumes/conf-sogo-custom-fulllogopng
volumes/conf-sogo-custom-themejs
volumes/conf-sogo-custom-sogojs
