#
# Roundcube state/backup include patterns for Restic
# Syntax reference: https://pkg.go.dev/path/filepath#Glob
# Restic --files-from: https://restic.readthedocs.io/en/stable/040_backup.html#including-files
# List here what you want to save during backup : volumes or file Path



state/unbound-mailcow.env 

volumes/hooks-unbound
volumes/conf-unbound-unboundconf
state/clamd-mailcow.env 

volumes/conf-clamav-
volumes/clamd-db-vol-1
state/sogo-mailcow.env 

volumes/hooks-sogo
volumes/conf-sogo-
volumes/web-inc-initdbincphp
volumes/conf-sogo-custom-faviconico
volumes/conf-sogo-custom-shortlogosvg
volumes/conf-sogo-custom-fulllogosvg
volumes/conf-sogo-custom-fulllogopng
volumes/conf-sogo-custom-themejs
volumes/conf-sogo-custom-sogojs
volumes/mysql-socket-vol-1
volumes/sogo-web-vol-1
volumes/sogo-userdata-backup-vol-1
state/dovecot-mailcow.env 

volumes/hooks-dovecot
volumes/conf-dovecot
volumes/assets-ssl
volumes/conf-sogo-
volumes/phpfpm-sogo-sso-
volumes/vmail-vol-1
volumes/vmail-index-vol-1
volumes/crypt-vol-1
volumes/rspamd-custom-
volumes/assets-templates
volumes/rspamd-vol-1
volumes/mysql-socket-vol-1
state/postfix-tlspol-mailcow.env 

volumes/postfix-tlspol-vol-1
state/nginx-mailcow.env 

volumes/data-web
volumes/conf-rspamd-dynmaps
volumes/assets-ssl-
volumes/conf-nginx-
volumes/conf-rspamd-metaexporter
volumes/dovecot-auth-mailcowauthphp
volumes/web-inc-functionsincphp
volumes/web-inc-functionsauthincphp
volumes/web-inc-sessionsincphp
volumes/sogo-web-vol-1
state/dockerapi-mailcow.env 

volumes/run-dockersock
