#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import os

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

# This is specific to you module, so you need to change it accordingly.


def generate_random_password(length):
    random_bytes = os.urandom(length)
    password = random_bytes.hex()
    return password[:length]


# agent.dump_env()
MYSQL_INITDB_SKIP_TZINFO = data.get("MYSQL_INITDB_SKIP_TZINFO", "1")
TZ = data.get("TZ", "UTC")
MYSQL_ROOT_PASSWORD = generate_random_password(16)
MYSQL_DATABASE = "mailcow"
MYSQL_USER = "mailcow"
MYSQL_PASSWORD = generate_random_password(16)

mysql_mailcow = {
    "MYSQL_INITDB_SKIP_TZINFO": MYSQL_INITDB_SKIP_TZINFO,
    "TZ": TZ,
    "MYSQL_ROOT_PASSWORD": MYSQL_ROOT_PASSWORD,
    "MYSQL_DATABASE": MYSQL_DATABASE,
    "MYSQL_USER": MYSQL_USER,
    "MYSQL_PASSWORD": MYSQL_PASSWORD,
}
agent.write_envfile("mysql-mailcow.env", mysql_mailcow)
REDISPASS = generate_random_password(16)
REDISMASTERPASS = generate_random_password(16)
redis = {"REDISPASS": REDISPASS, "REDISMASTERPASS": REDISMASTERPASS}

agent.write_envfile("redis.env", redis)
