#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import os

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

# This is specific to you module, so you need to change it accordingly.


def generate_random_password(length):
    # Generate random bytes and convert them to a hexadecimal string
    random_bytes = os.urandom(length)
    password = random_bytes.hex()
    return password[:length]


# just before starting systemd unit
# agent.dump_env()
MYSQL_INITDB_SKIP_TZINFO = data.get("MYSQL_INITDB_SKIP_TZINFO", "1") 
TZ = data.get("TZ", "${TZ}") 
MYSQL_ROOT_PASSWORD = data.get("MYSQL_ROOT_PASSWORD", "${DBROOT}") 
MYSQL_DATABASE = data.get("MYSQL_DATABASE", "${DBNAME}") 
MYSQL_USER = data.get("MYSQL_USER", "${DBUSER}") 
MYSQL_PASSWORD = data.get("MYSQL_PASSWORD", "${DBPASS}") 
 
mysql-mailcow = { 
 "MYSQL_INITDB_SKIP_TZINFO" : MYSQL_INITDB_SKIP_TZINFO ,
 "TZ" : TZ ,
 "MYSQL_ROOT_PASSWORD" : MYSQL_ROOT_PASSWORD ,
 "MYSQL_DATABASE" : MYSQL_DATABASE ,
 "MYSQL_USER" : MYSQL_USER ,
 "MYSQL_PASSWORD" : MYSQL_PASSWORD ,
} 
agent.write_envfile("mysql-mailcow.env", mysql-mailcow) 
