#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import sys
import json
import agent

def read_env_or_default(env_file, defaults):
    if os.path.exists(env_file):
        data = agent.read_envfile(env_file)
        result = {}
        for key, default in defaults.items():
            result[key] = data.get(key, default)
        return result
    return defaults

config = {}

config["host"] = os.getenv("TRAEFIK_HOST","")
config["http2https"] = os.getenv("TRAEFIK_HTTP2HTTPS") == "True"
config["lets_encrypt"] = os.getenv("TRAEFIK_LETS_ENCRYPT") == "True"

unbound_defaults = {
    "TZ": "UTC",
    "SKIP_UNBOUND_HEALTHCHECK": "n",
}
unbound_config = read_env_or_default("unbound-mailcow.env", unbound_defaults)
config.update(unbound_config)

clamd_defaults = {
    "TZ": "UTC",
    "SKIP_CLAMD": "n",
}
clamd_config = read_env_or_default("clamd-mailcow.env", clamd_defaults)
config.update(clamd_config)

sogo_defaults = {
    "MAILCOW_PASS_SCHEME": "BLF-CRYPT",
    "MASTER": "y",
    "DBPASS": "",
    "MAILCOW_HOSTNAME": "",
    "SOGO_URL_ENCRYPTION_KEY": "",
    "SKIP_SOGO": "n",
    "REDIS_SLAVEOF_PORT": "",
    "ACL_ANYONE": "disallow",
    "ALLOW_ADMIN_EMAIL_LOGIN": "n",
    "REDISPASS": "",
    "DBUSER": "mailcow",
    "IPV4_NETWORK": "172.22.1",
    "SOGO_EXPIRE_SESSION": "480",
    "REDIS_SLAVEOF_IP": "",
    "DBNAME": "mailcow",
    "TZ": "UTC",
    "LOG_LINES": "9999",
}
sogo_config = read_env_or_default("sogo-mailcow.env", sogo_defaults)
config.update(sogo_config)

dovecot_defaults = {
    "DOVECOT_MASTER_USER": "",
    "DOVEADM_REPLICA_PORT": "",
    "MAILCOW_HOSTNAME": "",
    "IPV4_NETWORK": "172.22.1",
    "ALLOW_ADMIN_EMAIL_LOGIN": "n",
    "MAILDIR_GC_TIME": "7200",
    "SKIP_FTS": "y",
    "FTS_PROCS": "3",
    "DOVECOT_MASTER_PASS": "",
    "LOG_LINES": "9999",
    "DBPASS": "",
    "MAILCOW_PASS_SCHEME": "BLF-CRYPT",
    "ACL_ANYONE": "disallow",
    "MAILDIR_SUB": "",
    "MASTER": "y",
    "REDIS_SLAVEOF_IP": "",
    "FTS_HEAP": "512",
    "REDISPASS": "",
    "MAILCOW_REPLICA_IP": "",
    "DBNAME": "mailcow",
    "DBUSER": "mailcow",
    "TZ": "UTC",
    "REDIS_SLAVEOF_PORT": "",
    "COMPOSE_PROJECT_NAME": "mailcow-dockerized",
}
dovecot_config = read_env_or_default("dovecot-mailcow.env", dovecot_defaults)
config.update(dovecot_config)

postfix_tlspol_defaults = {
    "LOG_LINES": "9999",
    "TZ": "UTC",
    "REDIS_SLAVEOF_IP": "",
    "REDIS_SLAVEOF_PORT": "",
    "REDISPASS": "",
    "DEV_MODE": "n",
}
postfix_tlspol_config = read_env_or_default("postfix-tlspol-mailcow.env", postfix_tlspol_defaults)
config.update(postfix_tlspol_config)

nginx_defaults = {
    "HTTPS_PORT": "443",
    "MAILCOW_HOSTNAME": "",
    "ENABLE_IPV6": "true",
    "PHPFPMHOST": "",
    "RSPAMDHOST": "",
    "REDISHOST": "",
    "NGINX_USE_PROXY_PROTOCOL": "n",
    "TZ": "UTC",
    "SKIP_RSPAMD": "n",
    "TRUSTED_PROXIES": "",
    "IPV4_NETWORK": "172.22.1",
    "SKIP_SOGO": "n",
    "HTTP_REDIRECT": "n",
    "HTTP_PORT": "80",
    "ADDITIONAL_SERVER_NAMES": "",
    "SOGOHOST": "",
}
nginx_config = read_env_or_default("nginx-mailcow.env", nginx_defaults)
config.update(nginx_config)

dockerapi_defaults = {
    "REDIS_SLAVEOF_PORT": "",
    "REDISPASS": "",
    "DBROOT": "",
    "TZ": "UTC",
    "REDIS_SLAVEOF_IP": "",
}
dockerapi_config = read_env_or_default("dockerapi-mailcow.env", dockerapi_defaults)
config.update(dockerapi_config)

olefy_defaults = {
    "TZ": "UTC",
    "OLEFY_BINDPORT": "10055",
    "OLEFY_OLEVBA_PATH": "/usr/bin/olevba",
    "SKIP_OLEFY": "n",
    "OLEFY_BINDADDRESS": "0.0.0.0",
    "OLEFY_TMPDIR": "/tmp",
    "OLEFY_PYTHON_PATH": "/usr/bin/python3",
    "OLEFY_LOGLVL": "20",
    "OLEFY_MINLENGTH": "500",
    "OLEFY_DEL_TMP": "1",
}
olefy_config = read_env_or_default("olefy-mailcow.env", olefy_defaults)
config.update(olefy_config)

mysql_defaults = {
    "MYSQL_USER": "mailcow",
    "MYSQL_PASSWORD": "",
    "MYSQL_INITDB_SKIP_TZINFO": "1",
    "TZ": "UTC",
    "MYSQL_ROOT_PASSWORD": "",
    "MYSQL_DATABASE": "mailcow",
}
mysql_config = read_env_or_default("mysql-mailcow.env", mysql_defaults)
config.update(mysql_config)

postfix_defaults = {
    "REDIS_SLAVEOF_IP": "",
    "REDIS_SLAVEOF_PORT": "",
    "REDISPASS": "",
    "SPAMHAUS_DQS_KEY": "",
    "LOG_LINES": "9999",
    "DBNAME": "mailcow",
    "DBUSER": "mailcow",
    "MAILCOW_HOSTNAME": "",
    "TZ": "UTC",
    "DBPASS": "",
}
postfix_config = read_env_or_default("postfix-mailcow.env", postfix_defaults)
config.update(postfix_config)

memcached_defaults = {
    "TZ": "UTC",
}
memcached_config = read_env_or_default("memcached-mailcow.env", memcached_defaults)
config.update(memcached_config)

acme_defaults = {
    "ONLY_MAILCOW_HOSTNAME": "n",
    "REDIS_SLAVEOF_IP": "",
    "REDIS_SLAVEOF_PORT": "",
    "LE_STAGING": "n",
    "SNAT6_TO_SOURCE": "n",
    "ADDITIONAL_SAN": "",
    "SKIP_LETS_ENCRYPT": "n",
    "COMPOSE_PROJECT_NAME": "mailcow-dockerized",
    "DIRECTORY_URL": "",
    "SKIP_HTTP_VERIFICATION": "n",
    "REDISPASS": "",
    "SNAT_TO_SOURCE": "n",
    "LOG_LINES": "9999",
    "AUTODISCOVER_SAN": "y",
    "MAILCOW_HOSTNAME": "",
    "DBPASS": "",
    "ENABLE_SSL_SNI": "n",
    "TZ": "UTC",
    "DBNAME": "mailcow",
    "DBUSER": "mailcow",
    "SKIP_IP_CHECK": "n",
}
acme_config = read_env_or_default("acme-mailcow.env", acme_defaults)
config.update(acme_config)

netfilter_defaults = {
    "REDIS_SLAVEOF_PORT": "",
    "TZ": "UTC",
    "IPV4_NETWORK": "172.22.1",
    "IPV6_NETWORK": "fd4d:6169:6c63:6f77::/64",
    "SNAT_TO_SOURCE": "n",
    "REDIS_SLAVEOF_IP": "",
    "REDISPASS": "",
    "MAILCOW_REPLICA_IP": "",
    "DISABLE_NETFILTER_ISOLATION_RULE": "n",
    "SNAT6_TO_SOURCE": "n",
}
netfilter_config = read_env_or_default("netfilter-mailcow.env", netfilter_defaults)
config.update(netfilter_config)

watchdog_defaults = {
    "NGINX_THRESHOLD": "5",
    "PHPFPM_THRESHOLD": "5",
    "OLEFY_THRESHOLD": "5",
    "MAILQ_THRESHOLD": "20",
    "IPV6_NETWORK": "fd4d:6169:6c63:6f77::/64",
    "DBROOT": "",
    "USE_WATCHDOG": "n",
    "WATCHDOG_NOTIFY_WEBHOOK": "",
    "REDIS_THRESHOLD": "5",
    "TZ": "UTC",
    "SKIP_LETS_ENCRYPT": "n",
    "HTTPS_PORT": "443",
    "MYSQL_REPLICATION_THRESHOLD": "1",
    "RSPAMD_THRESHOLD": "5",
    "MAILQ_CRIT": "30",
    "DBUSER": "mailcow",
    "IP_BY_DOCKER_API": "0",
    "CHECK_UNBOUND": "1",
    "POSTFIX_TLSPOL_THRESHOLD": "8",
    "RATELIMIT_THRESHOLD": "1",
    "WATCHDOG_NOTIFY_BAN": "y",
    "COMPOSE_PROJECT_NAME": "mailcow-dockerized",
    "SKIP_SOGO": "n",
    "UNBOUND_THRESHOLD": "5",
    "MYSQL_THRESHOLD": "5",
    "CLAMD_THRESHOLD": "15",
    "DOVECOT_THRESHOLD": "12",
    "DBNAME": "mailcow",
    "WATCHDOG_SUBJECT": "Watchdog ALERT",
    "WATCHDOG_NOTIFY_WEBHOOK_BODY": "",
    "WATCHDOG_MYSQL_REPLICATION_CHECKS": "n",
    "WATCHDOG_VERBOSE": "n",
    "IPV4_NETWORK": "172.22.1",
    "SKIP_OLEFY": "n",
    "REDIS_SLAVEOF_PORT": "",
    "LOG_LINES": "9999",
    "WATCHDOG_NOTIFY_START": "y",
    "REDIS_SLAVEOF_IP": "",
    "REDISPASS": "",
    "EXTERNAL_CHECKS_THRESHOLD": "1",
    "SOGO_THRESHOLD": "3",
    "POSTFIX_THRESHOLD": "8",
    "DOVECOT_REPL_THRESHOLD": "20",
    "WATCHDOG_EXTERNAL_CHECKS": "n",
    "MAILCOW_HOSTNAME": "",
    "FAIL2BAN_THRESHOLD": "1",
    "ACME_THRESHOLD": "1",
    "DEV_MODE": "n",
    "DBPASS": "",
    "WATCHDOG_NOTIFY_EMAIL": "",
    "SKIP_CLAMD": "n",
}
watchdog_config = read_env_or_default("watchdog-mailcow.env", watchdog_defaults)
config.update(watchdog_config)

redis_defaults = {
    "TZ": "UTC",
    "REDISPASS": "",
    "REDISMASTERPASS": "",
}
redis_config = read_env_or_default("redis-mailcow.env", redis_defaults)
config.update(redis_config)

rspamd_defaults = {
    "SPAMHAUS_DQS_KEY": "",
    "TZ": "UTC",
    "IPV4_NETWORK": "172.22.1",
    "IPV6_NETWORK": "fd4d:6169:6c63:6f77::/64",
    "REDIS_SLAVEOF_IP": "",
    "REDIS_SLAVEOF_PORT": "",
    "REDISPASS": "",
}
rspamd_config = read_env_or_default("rspamd-mailcow.env", rspamd_defaults)
config.update(rspamd_config)

ofelia_defaults = {
    "TZ": "UTC",
    "COMPOSE_PROJECT_NAME": "mailcow-dockerized",
}
ofelia_config = read_env_or_default("ofelia-mailcow.env", ofelia_defaults)
config.update(ofelia_config)

php_fpm_defaults = {
    "MAILCOW_HOSTNAME": "",
    "IMAPS_PORT": "993",
    "API_KEY_READ_ONLY": "",
    "SKIP_CLAMD": "n",
    "ALLOW_ADMIN_EMAIL_LOGIN": "n",
    "MASTER": "y",
    "DEMO_MODE": "n",
    "LOG_LINES": "9999",
    "POP_PORT": "110",
    "POPS_PORT": "995",
    "IPV4_NETWORK": "172.22.1",
    "API_KEY": "",
    "SKIP_FTS": "y",
    "DEV_MODE": "n",
    "ADDITIONAL_SERVER_NAMES": "",
    "DBUSER": "mailcow",
    "IPV6_NETWORK": "fd4d:6169:6c63:6f77::/64",
    "API_ALLOW_FROM": "127.0.0.1",
    "DBNAME": "mailcow",
    "DBPASS": "",
    "MAILCOW_PASS_SCHEME": "BLF-CRYPT",
    "SIEVE_PORT": "4190",
    "SKIP_OLEFY": "n",
    "TZ": "UTC",
    "CLUSTERMODE": "",
    "REDIS_SLAVEOF_PORT": "",
    "IMAP_PORT": "143",
    "SUBMISSION_PORT": "587",
    "SMTPS_PORT": "465",
    "SMTP_PORT": "25",
    "SKIP_SOGO": "n",
    "REDIS_SLAVEOF_IP": "",
    "REDISPASS": "",
    "WEBAUTHN_ONLY_TRUSTED_VENDORS": "n",
    "COMPOSE_PROJECT_NAME": "mailcow-dockerized",
}
php_fpm_config = read_env_or_default("php-fpm-mailcow.env", php_fpm_defaults)
config.update(php_fpm_config)

json.dump(config, fp=sys.stdout)
